name: Build Status

on:
    push:
        branches: [main]
    pull_request:
        types: [ opened, synchronize ]

env:
    DATABASE_URL: localhost

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      -
        name: Cache Composer dependencies between workflows
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-${{ hashFiles('./backend/composer.lock') }}
      -
        name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: ./backend
          #php_extensions to ignore
          args: --ignore-platform-req=ext-gd  --ignore-platform-req=ext-zip
      -
        name: run tests
        working-directory: ./backend
        run: composer tests
      -
        name: checkstyle
        working-directory: ./backend
        run: composer cs